linters-settings:
  custom:
    loglinter:
      type: "module"
      description: "Checks log messages for established rules"
      settings:
        rules:
          - lowercase-first-letter
          - english-only
          - no-special-chars
          - no-sensitive-data

linters:
  enable:
    - loglinter
  disable-all: false
